version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "devmysql"
    ports:
      - "13306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "81:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api

  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network









